[package]
name = "Payroll"
version = "1.0.0"
authors = []

[addresses]
bulk_payroll = "_"

company_payroll = "_"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-framework.git"
rev = "mainnet"
subdir = "aptos-framework"

[dev-dependencies]
